### ISSUE TITLE
Issue compiling with new instruments

### ISSUE THREAD

**Issue by z00t** [digero/maestro#10]
Hello,

Long time Maestro user- I've moved on to Shroud of the Avatar and have begun porting/augmenting Maestro for use in SotA.

I am running across an issue compiling a new sf2:

GenerateSoundFontInfo.CheckUpToDate:
GenerateSoundFontInfo:
     [java] Sample Directory: X:\Git\SotA-Composer\audio\LotroInstruments
     [java] java.lang.NullPointerException
     [java] 	at java.util.TreeMap.put(Unknown Source)
     [java] 	at java.util.TreeSet.add(Unknown Source)
     [java] 	at com.digero.tools.soundfont.StandardInstrumentInfo.<init>(StandardInstrumentInfo.java:36)
     [java] 	at com.digero.tools.soundfont.StandardInstrumentInfo.<init>(StandardInstrumentInfo.java:22)
     [java] 	at com.digero.tools.soundfont.GenerateSoundFontInfo.run(GenerateSoundFontInfo.java:140)
     [java] 	at com.digero.tools.soundfont.GenerateSoundFontInfo.main(GenerateSoundFontInfo.java:20)

Was hoping to get some insight from you about a few other things also, but the email link you have in contact is unusable (recaptcha v1 on mailhide is obsolete)

**Comment by z00t** [comment]
I was able to bypass the check and get a compile with the new instrument- I'd still like to discuss a few things if you would? :)
